name: serial_communication
homepage: https://github.com/bjssoftsolutions/serial_communication
version: 0.0.2
description: An Android Plugin for Serial Communication which allows you to read and write the data through the available ports

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.example.serial_communication
        pluginClass: SerialCommunicationPlugin

 